import { z } from 'zod'
import fs from 'fs'
import path from 'path'

const envSchema = z.object({
  DATABASE_URL: z.string().url(),
  SUPABASE_URL: z.string().url(),
  SUPABASE_ANON_KEY: z.string().min(10),
  SUPABASE_SERVICE_ROLE_KEY: z.string().min(10),
  SUPABASE_BUCKET_INPUT: z.string().min(1),
  SUPABASE_BUCKET_OUTPUT: z.string().min(1),
  SUPABASE_BUCKET_UPLOADS: z.string().min(1).optional(),
  SUPABASE_BUCKET_OUTPUTS: z.string().min(1).optional(),
  FRONTEND_URL: z.string().url(),
  STRIPE_SECRET_KEY: z.string().min(10),
  STRIPE_WEBHOOK_SECRET: z.string().min(10),
  STRIPE_PRICE_ID_MONTHLY: z.string().min(1).optional(),
  STRIPE_PRICE_ID_STARTER: z.string().min(1),
  STRIPE_PRICE_ID_CREATOR: z.string().min(1),
  STRIPE_PRICE_ID_STUDIO: z.string().min(1),
  STRIPE_MODE: z.string().optional(),
  STRIPE_PRICE_ID_STARTER_ANNUAL: z.string().min(1).optional(),
  STRIPE_PRICE_ID_CREATOR_ANNUAL: z.string().min(1).optional(),
  STRIPE_PRICE_ID_STUDIO_ANNUAL: z.string().min(1).optional(),
  STRIPE_PRICE_ID_TRIAL: z.string().min(1).optional(),
  STRIPE_TEST_SECRET_KEY: z.string().min(10).optional(),
  STRIPE_TEST_WEBHOOK_SECRET: z.string().min(10).optional(),
  STRIPE_TEST_PRICE_ID_STARTER: z.string().min(1).optional(),
  STRIPE_TEST_PRICE_ID_CREATOR: z.string().min(1).optional(),
  STRIPE_TEST_PRICE_ID_STUDIO: z.string().min(1).optional(),
  STRIPE_TEST_PRICE_ID_STARTER_ANNUAL: z.string().min(1).optional(),
  STRIPE_TEST_PRICE_ID_CREATOR_ANNUAL: z.string().min(1).optional(),
  STRIPE_TEST_PRICE_ID_STUDIO_ANNUAL: z.string().min(1).optional(),
  STRIPE_TEST_PRICE_ID_TRIAL: z.string().min(1).optional(),
  APP_URL: z.string().url(),
  APP_BASE_URL: z.string().url().optional(),
  AI_PROVIDER: z.string().optional(),
  AI_API_KEY: z.string().optional(),
  AI_MODEL: z.string().optional(),
  OLLAMA_BASE_URL: z.string().url().optional(),
  OLLAMA_GEMMA_MODEL: z.string().optional(),
  OLLAMA_FALLBACK_MODEL: z.string().optional(),
  OLLAMA_TIMEOUT_MS: z.string().optional(),
  OLLAMA_AUTH_HEADER: z.string().optional(),
  CF_ACCESS_CLIENT_ID: z.string().optional(),
  CF_ACCESS_CLIENT_SECRET: z.string().optional(),
  RETENTION_AI_PROVIDER_ORDER: z.string().optional(),
  RETENTION_AI_RETRIES: z.string().optional(),
  RETENTION_AI_BACKOFF_BASE_MS: z.string().optional(),
  RETENTION_LLM_DECISION_TIMEOUT_MS: z.string().optional(),
  HUGGINGFACE_API_KEY: z.string().optional(),
  HF_API_TOKEN: z.string().optional(),
  HF_RETENTION_MODEL: z.string().optional(),
  HF_SENTIMENT_MODEL: z.string().optional(),
  HF_LLAMA_PRIMARY_MODEL: z.string().optional(),
  HF_LLAMA_FALLBACK_MODELS: z.string().optional(),
  HF_LLAMA_BATCH_SIZE: z.string().optional(),
  LLAMA_PROVIDER: z.string().optional(),
  LLAMA_LOCAL_INFERENCE_URL: z.string().optional(),
  LLAMA_LOCAL_API_KEY: z.string().optional(),
  LLAMA_MAX_RETRIES: z.string().optional(),
  LLAMA_BACKOFF_BASE_MS: z.string().optional(),
  LLAMA_DECISION_TIMEOUT_MS: z.string().optional(),
  LLAMA_REQUEST_TIMEOUT_MS: z.string().optional(),
  VIBECUT_UPLOAD_ANALYZE_MAX_MS: z.string().optional(),
  VIBECUT_UPLOAD_FFPROBE_TIMEOUT_MS: z.string().optional(),
  VIBECUT_UPLOAD_FRAME_SCAN_TIMEOUT_MS: z.string().optional(),
  VIBECUT_UPLOAD_TRANSCRIPT_TIMEOUT_MS: z.string().optional(),
  VIBECUT_UPLOAD_SKIP_TRANSCRIPT: z.string().optional(),
})

export const getEnv = () => {
  const raw = {
    DATABASE_URL: process.env.DATABASE_URL ?? '',
    SUPABASE_URL: process.env.SUPABASE_URL ?? '',
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY ?? '',
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY ?? '',
    SUPABASE_BUCKET_INPUT: process.env.SUPABASE_BUCKET_INPUT ?? '',
    SUPABASE_BUCKET_OUTPUT: process.env.SUPABASE_BUCKET_OUTPUT ?? '',
    SUPABASE_BUCKET_UPLOADS: process.env.SUPABASE_BUCKET_UPLOADS ?? '',
    SUPABASE_BUCKET_OUTPUTS: process.env.SUPABASE_BUCKET_OUTPUTS ?? '',
    FRONTEND_URL: process.env.FRONTEND_URL ?? '',
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY ?? '',
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET ?? '',
    STRIPE_PRICE_ID_MONTHLY: process.env.STRIPE_PRICE_ID_MONTHLY ?? '',
    STRIPE_PRICE_ID_STARTER: process.env.STRIPE_PRICE_ID_STARTER ?? '',
    STRIPE_PRICE_ID_CREATOR: process.env.STRIPE_PRICE_ID_CREATOR ?? '',
    STRIPE_PRICE_ID_STUDIO: process.env.STRIPE_PRICE_ID_STUDIO ?? '',
    STRIPE_MODE: process.env.STRIPE_MODE ?? '',
    STRIPE_PRICE_ID_STARTER_ANNUAL: process.env.STRIPE_PRICE_ID_STARTER_ANNUAL ?? '',
    STRIPE_PRICE_ID_CREATOR_ANNUAL: process.env.STRIPE_PRICE_ID_CREATOR_ANNUAL ?? '',
    STRIPE_PRICE_ID_STUDIO_ANNUAL: process.env.STRIPE_PRICE_ID_STUDIO_ANNUAL ?? '',
    STRIPE_PRICE_ID_TRIAL: process.env.STRIPE_PRICE_ID_TRIAL ?? '',
    STRIPE_TEST_SECRET_KEY: process.env.STRIPE_TEST_SECRET_KEY ?? '',
    STRIPE_TEST_WEBHOOK_SECRET: process.env.STRIPE_TEST_WEBHOOK_SECRET ?? '',
    STRIPE_TEST_PRICE_ID_STARTER: process.env.STRIPE_TEST_PRICE_ID_STARTER ?? '',
    STRIPE_TEST_PRICE_ID_CREATOR: process.env.STRIPE_TEST_PRICE_ID_CREATOR ?? '',
    STRIPE_TEST_PRICE_ID_STUDIO: process.env.STRIPE_TEST_PRICE_ID_STUDIO ?? '',
    STRIPE_TEST_PRICE_ID_STARTER_ANNUAL: process.env.STRIPE_TEST_PRICE_ID_STARTER_ANNUAL ?? '',
    STRIPE_TEST_PRICE_ID_CREATOR_ANNUAL: process.env.STRIPE_TEST_PRICE_ID_CREATOR_ANNUAL ?? '',
    STRIPE_TEST_PRICE_ID_STUDIO_ANNUAL: process.env.STRIPE_TEST_PRICE_ID_STUDIO_ANNUAL ?? '',
    STRIPE_TEST_PRICE_ID_TRIAL: process.env.STRIPE_TEST_PRICE_ID_TRIAL ?? '',
    APP_URL: process.env.APP_URL ?? '',
    APP_BASE_URL: process.env.APP_BASE_URL ?? '',
    AI_PROVIDER: process.env.AI_PROVIDER,
    AI_API_KEY: process.env.AI_API_KEY,
    AI_MODEL: process.env.AI_MODEL,
    OLLAMA_BASE_URL: process.env.OLLAMA_BASE_URL,
    OLLAMA_GEMMA_MODEL: process.env.OLLAMA_GEMMA_MODEL,
    OLLAMA_FALLBACK_MODEL: process.env.OLLAMA_FALLBACK_MODEL,
    OLLAMA_TIMEOUT_MS: process.env.OLLAMA_TIMEOUT_MS,
    OLLAMA_AUTH_HEADER: process.env.OLLAMA_AUTH_HEADER,
    CF_ACCESS_CLIENT_ID: process.env.CF_ACCESS_CLIENT_ID,
    CF_ACCESS_CLIENT_SECRET: process.env.CF_ACCESS_CLIENT_SECRET,
    RETENTION_AI_PROVIDER_ORDER: process.env.RETENTION_AI_PROVIDER_ORDER,
    RETENTION_AI_RETRIES: process.env.RETENTION_AI_RETRIES,
    RETENTION_AI_BACKOFF_BASE_MS: process.env.RETENTION_AI_BACKOFF_BASE_MS,
    RETENTION_LLM_DECISION_TIMEOUT_MS: process.env.RETENTION_LLM_DECISION_TIMEOUT_MS,
    HUGGINGFACE_API_KEY: process.env.HUGGINGFACE_API_KEY,
    HF_API_TOKEN: process.env.HF_API_TOKEN,
    HF_RETENTION_MODEL: process.env.HF_RETENTION_MODEL,
    HF_SENTIMENT_MODEL: process.env.HF_SENTIMENT_MODEL,
    HF_LLAMA_PRIMARY_MODEL: process.env.HF_LLAMA_PRIMARY_MODEL,
    HF_LLAMA_FALLBACK_MODELS: process.env.HF_LLAMA_FALLBACK_MODELS,
    HF_LLAMA_BATCH_SIZE: process.env.HF_LLAMA_BATCH_SIZE,
    LLAMA_PROVIDER: process.env.LLAMA_PROVIDER,
    LLAMA_LOCAL_INFERENCE_URL: process.env.LLAMA_LOCAL_INFERENCE_URL,
    LLAMA_LOCAL_API_KEY: process.env.LLAMA_LOCAL_API_KEY,
    LLAMA_MAX_RETRIES: process.env.LLAMA_MAX_RETRIES,
    LLAMA_BACKOFF_BASE_MS: process.env.LLAMA_BACKOFF_BASE_MS,
    LLAMA_DECISION_TIMEOUT_MS: process.env.LLAMA_DECISION_TIMEOUT_MS,
    LLAMA_REQUEST_TIMEOUT_MS: process.env.LLAMA_REQUEST_TIMEOUT_MS,
    VIBECUT_UPLOAD_ANALYZE_MAX_MS: process.env.VIBECUT_UPLOAD_ANALYZE_MAX_MS,
    VIBECUT_UPLOAD_FFPROBE_TIMEOUT_MS: process.env.VIBECUT_UPLOAD_FFPROBE_TIMEOUT_MS,
    VIBECUT_UPLOAD_FRAME_SCAN_TIMEOUT_MS: process.env.VIBECUT_UPLOAD_FRAME_SCAN_TIMEOUT_MS,
    VIBECUT_UPLOAD_TRANSCRIPT_TIMEOUT_MS: process.env.VIBECUT_UPLOAD_TRANSCRIPT_TIMEOUT_MS,
    VIBECUT_UPLOAD_SKIP_TRANSCRIPT: process.env.VIBECUT_UPLOAD_SKIP_TRANSCRIPT,
  }
  const parsed = envSchema.safeParse(raw)
  if (parsed.success) return parsed.data
  // return raw (possibly invalid) to allow running in dev / stub modes
  return raw as any
}

export const writeEnvFile = (targetPath: string, values: Record<string,string>) => {
  const content = Object.entries(values)
    .map(([k,v]) => `${k}=${v}`)
    .join('\n')
  fs.mkdirSync(path.dirname(targetPath), { recursive: true })
  fs.writeFileSync(targetPath, content, { encoding: 'utf8' })
}

export type Env = z.infer<typeof envSchema>
