ALTER TABLE "UserSettings"
  ADD COLUMN IF NOT EXISTS "jumpCuts" BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS "transitions" BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS "soundFx" BOOLEAN DEFAULT true;
